"""Drop Reference.version

Revision ID: 08220629322a
Revises: 0d9a434c70b1
Create Date: 2016-06-14 15:45:44.437295

"""

from __future__ import unicode_literals

# revision identifiers, used by Alembic.
revision = '08220629322a'
down_revision = u'0d9a434c70b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references') as batch_op:
        batch_op.drop_column('version')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
