"""Add Reference.version

Revision ID: 0d9a434c70b1
Revises: abe71597ab2c
Create Date: 2016-06-13 15:04:20.614210

"""

from __future__ import unicode_literals

# revision identifiers, used by Alembic.
revision = '0d9a434c70b1'
down_revision = u'abe71597ab2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('version', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('references', 'version')
    ### end Alembic commands ###
