"""Drop TranscriptProteinLink table

Revision ID: 10692e9f4836
Revises: 1bf1b52f057
Create Date: 2015-11-09 16:11:50.425722

"""

from __future__ import unicode_literals

# revision identifiers, used by Alembic.
revision = '10692e9f4836'
down_revision = u'1bf1b52f057'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_protein_links')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_protein_links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transcript_accession', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('protein_accession', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'transcript_protein_links_pkey')
    )
    ### end Alembic commands ###
