"""Drop BatchJob.download_url

Revision ID: 1ed411f9fdfa
Revises: 10692e9f4836
Create Date: 2015-11-09 17:24:15.630818

"""

from __future__ import unicode_literals

# revision identifiers, used by Alembic.
revision = '1ed411f9fdfa'
down_revision = u'10692e9f4836'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_jobs') as batch_op:
        batch_op.drop_column('download_url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_jobs') as batch_op:
        batch_op.add_column(sa.Column('download_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    ### end Alembic commands ###
