"""Transcript protein links have nullable transcript and unique protein

Revision ID: 3492d2ee8884
Revises: 4bafcc5086dd
Create Date: 2015-09-25 15:11:45.562392

"""

from __future__ import unicode_literals

# revision identifiers, used by Alembic.
revision = '3492d2ee8884'
down_revision = u'4bafcc5086dd'

from alembic import op
import sqlalchemy as sa


# We are adding a unique constraint here, so actually we should first make
# sure there are no duplicate entries. However, this is highly unlikely, so we
# don't bother prepping the migration for that.
#
# http://skien.cc/blog/2014/01/31/adding-unique-contraints-after-the-fact-in-sqlalchemy/


# We want to be compatible with at least SQLite and PostgreSQL. This means
# using `batch_alter_table` for operations yielding an ALTER TABLE statement.
# However, we also have indices on the table and this causes problems with
# `batch_alter_table` (it seems indices are copied too, under the same name,
# which is invalid). To work around this, we wrap the batch operations in drop
# and create statements for the indices.
#
# http://alembic.readthedocs.org/en/latest/batch.html


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transcript_protein_links_transcript_accession', table_name='transcript_protein_links')
    op.drop_index('ix_transcript_protein_links_protein_accession', table_name='transcript_protein_links')
    with op.batch_alter_table('transcript_protein_links') as batch_op:
        batch_op.alter_column('transcript_accession',
                              existing_type=sa.VARCHAR(length=20),
                              nullable=True)
    op.create_index(op.f('ix_transcript_protein_links_transcript_accession'), 'transcript_protein_links', ['transcript_accession'], unique=True)
    op.create_index(op.f('ix_transcript_protein_links_protein_accession'), 'transcript_protein_links', ['protein_accession'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_protein_links_transcript_accession'), table_name='transcript_protein_links')
    op.drop_index(op.f('ix_transcript_protein_links_protein_accession'), table_name='transcript_protein_links')
    with op.batch_alter_table('transcript_protein_links') as batch_op:
        batch_op.alter_column('transcript_accession',
                              existing_type=sa.VARCHAR(length=20),
                              nullable=False)
    op.create_index('ix_transcript_protein_links_transcript_accession', 'transcript_protein_links', ['transcript_accession'], unique=True)
    op.create_index('ix_transcript_protein_links_protein_accession', 'transcript_protein_links', ['protein_accession'], unique=False)
    ### end Alembic commands ###
