"""Drop Reference.slice_* and Reference.download_url

Revision ID: abe71597ab2c
Revises: 8ed4dce84496
Create Date: 2016-06-10 13:32:02.796607

"""

from __future__ import unicode_literals

# revision identifiers, used by Alembic.
revision = 'abe71597ab2c'
down_revision = u'8ed4dce84496'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.drop_index('ix_references_download_url', table_name='references')
    op.drop_index('reference_slice', table_name='references')

    with op.batch_alter_table('references') as batch_op:
        batch_op.drop_column('slice_accession')
        batch_op.drop_column('slice_orientation')
        batch_op.drop_column('slice_start')
        batch_op.drop_column('download_url')
        batch_op.drop_column('slice_stop')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('slice_stop', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('references', sa.Column('download_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('references', sa.Column('slice_start', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('references', sa.Column('slice_orientation', sa.ENUM(u'forward', u'reverse', name='slice_orientation'), autoincrement=False, nullable=True))
    op.add_column('references', sa.Column('slice_accession', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index('reference_slice', 'references', ['slice_accession', 'slice_start', 'slice_stop', 'slice_orientation'], unique=True)
    op.create_index('ix_references_download_url', 'references', ['download_url'], unique=True)
    ### end Alembic commands ###
